### ISSUE TITLE
Comparison with "Report to SCM" config on Wercker

### ISSUE THREAD

**Issue by olliebennett** [mbrevda/wercker-step-github-status#1]
It's probably worth pointing out that this custom step is only required if you need more flexible control over what status updates are sent to GitHub.

Wercker supports a "Report to SCM" (i.e. Source Control Management / GitHub) config option on each pipeline, which ensures the build status.

![image](https://cloud.githubusercontent.com/assets/1068525/22424135/f81a05c2-e6ec-11e6-88c5-99283145a5b9.png)

Is it worth mentioning the differences in your README?

**Comment by mbrevda** [comment]
You are correct that this step is primarily for advanced use cases. The reason for this step (and other like it in the registry) are for sending additional statuses, such as [this use case](https://twitter.com/mbrevda/status/825381852345225217).

Ideally, there would be a way to extend wercker to send additional status messages, with specific details ([`context`/`description`/`target_url`](https://developer.github.com/v3/repos/statuses/#create-a-status)) and the ability to update the SCM at both the start and end of a pipeline/workflow. Then we could use a pipeline for proper updating and this step would be superfluous.

In the meantime, feel free to suggest a change via PR!
